# Generated by Django 2.2.12 on 2020-04-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegister', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='profileImg',
            field=models.CharField(default='photo.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='instructor',
            name='profileImg',
            field=models.CharField(default='photo.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='organisation',
            name='profileImg',
            field=models.CharField(default='photo.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='profileImg',
            field=models.CharField(default='photo.jpg', max_length=100),
        ),
    ]
