# Generated by Django 2.2.12 on 2020-05-01 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminUser',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('profileImg', models.CharField(default='photo.jpg', max_length=100)),
                ('date_of_reg', models.DateTimeField(default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='college',
            fields=[
                ('college_id', models.AutoField(primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=100)),
                ('university_type', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.BigIntegerField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('skill_set', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('profileImg', models.CharField(default='photo.jpg', max_length=100)),
                ('date_of_reg', models.DateTimeField(default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='instructor',
            fields=[
                ('instructor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.BigIntegerField()),
                ('subjects', models.CharField(max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('job_organisation_name', models.CharField(default='', max_length=200)),
                ('job_experience', models.CharField(default='', max_length=100)),
                ('job_location', models.CharField(default='', max_length=100)),
                ('job_state', models.CharField(default='', max_length=100)),
                ('job_type', models.CharField(max_length=8)),
                ('skills', models.CharField(default='', max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('profileImg', models.CharField(default='photo.jpg', max_length=100)),
                ('date_of_reg', models.DateTimeField(default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='organisation',
            fields=[
                ('organisation_id', models.AutoField(primary_key=True, serialize=False)),
                ('organisation_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.BigIntegerField()),
                ('state', models.CharField(default='', max_length=100)),
                ('gstin_no', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('profileImg', models.CharField(default='photo.jpg', max_length=100)),
                ('date_of_reg', models.DateTimeField(default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='studentUser',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.BigIntegerField()),
                ('birth_date', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('highest_qualification', models.CharField(default='', max_length=100)),
                ('university_name', models.CharField(default='', max_length=100)),
                ('roll_no', models.CharField(default='', max_length=100)),
                ('specialisation', models.CharField(default='', max_length=100)),
                ('college_state', models.CharField(default='', max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('skill_set', models.CharField(max_length=100)),
                ('profileImg', models.CharField(default='photo.jpg', max_length=100)),
                ('date_of_reg', models.DateTimeField(default=django.utils.timezone.now)),
                ('no_of_courses', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
